In [45]:
array(1:15, dim=c(3,5))

[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

In [40]:
matrix(1:15, 3, 5,  byrow=FALSE)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

In [13]:
array(1:15, dim = c(3, 5))

[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

In [16]:
m <- matrix(1:4, 2, 2)
inverse_m = solve(m)
m %*% inverse_m

[,1] [,2]
[1,] 1    0   
[2,] 0    1

In [31]:
cat("R is", "awesome")

R is awesome

In [96]:
a <- c(1,3,3,2)
a[1] # 1
length(a) # 3
sort(a)
rev(a)
unique(a)

[1] 1

[1] 4

[1] 1 2 3 3

[1] 2 3 3 1

[1] 1 3 2

In [54]:
fn <- function(a, b){
    return(c(a, b))
}
fn(1, 2)

[1] 1 2

In [90]:
m1 <- array(1:15, dim=c(3,5))
m2 <- matrix(1:15, 3, 5,  byrow=FALSE)
all(m1==m2)

dim(m2)
# colMeans(m2)
# rowMeans(m2)
# both gives:
# 1	4	7	10	13
# 2	5	8	11	14
# 3	6	9	12	15

# dim(m2)<- c(1, 15)
# m2

# t(m2)

[1] TRUE

[1] 3 5

In [ ]:
sum(1, 2) # 3
x <- c(1,3,3,2)
max(x) # 3
min(x) # 1
mean(x) # 2.25
median(x) # 2.5
var(x) # 0.9166
sd(x) # 0.9574
as.numeric(names(sort(-table(x))[1])) # 3, mode

[1] 3

[1] 3

[1] 1

[1] 2.25

[1] 2.5

[1] 0.9166667

[1] 0.9574271

[1] 3

In [20]:
pi # 3.14159265358979
3**2 # 9 
3^2 # 9
sqrt(9) # 3

abs(-3) # 3
round(pi, 2) # 3.14
floor(pi) # 3
ceiling(pi) # 4
trunc(pi) # 3

exp(1)
log(10) # 2.30258509299405
log(100, 10) # 2


[1] 3.141593

[1] 9

[1] 9

[1] 3

[1] 3

[1] 3.14

[1] 3

[1] 4

[1] 3

[1] 2.718282

[1] 2.302585

[1] 2

In [ ]:
a <- 7
b = 7 
print(a == b) # TRUE
mode(a) # numeric 
class(a) # numeric
typeof(a) # double

is.na(a) # FALSE
is.numeric(a) # TRUE
is.integer(a) # FALSE
is.double(a) # TRUE


[1] TRUE


[1] "numeric"

[1] "numeric"

[1] "double"

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

In [109]:
# a <- c(1,3,3,2)
# a[1] # 1
# length(a) # 3
# sort(a) # 1 2 3 3
# rev(a) # 2 3 3 1
# unique(a) # 1 3 2

b <- c(FALSE, TRUE, FALSE)
any(b) # TRUE, if any is true -> true
all(b) # FALSE, everything true -> true
which(b) # 2

[1] TRUE

[1] FALSE

[1] 2