# Matrices


In [6]:
array(1:5, dim=c(1,5)) # row vector
array(1:3, dim=c(3,1)) # col vector
array(1:15, dim=c(3,5))

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5

[,1]
[1,] 1   
[2,] 2   
[3,] 3

[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

In [8]:
matrix(1:15, 3, 5) # matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

In [20]:
m <- c(1, 2, 3, 4, 5, 6)
dim(m) <- c(3,2) 
m
dim(m) <- c(2,3) 
m

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [37]:
m <- matrix(1:4, 2, 2)
m + m
# m - m
m * m
# m / m
# 2 * m
m %*% m # dot

[,1] [,2]
[1,] 2    6   
[2,] 4    8

[,1] [,2]
[1,] 1     9  
[2,] 4    16

[,1] [,2]
[1,]  7   15  
[2,] 10   22

## $A^{-1}$


In [47]:
m <- matrix(1:4, 2, 2)
inverse_m <- solve(m)
inverse_m
m %*% inverse_m # identity matrix

[,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5

[,1] [,2]
[1,] 1    0   
[2,] 0    1

## $ax=b$

mx=m


In [54]:
m <- matrix(1:4, 2, 2)
solve(m, m)

# mx = m
# x = m * m^-1 (identity matrix)
m %*% solve(m)

[,1] [,2]
[1,] 1    0   
[2,] 0    1

[,1] [,2]
[1,] 1    0   
[2,] 0    1

In [66]:
m <- matrix(1:4, 2, 2)
colMeans(m)
rowMeans(m)

[1] 1.5 3.5

[1] 2 3

In [106]:
2^4; 2**4
paste("R is", "awesome")
cat("R is", "awesome")
cat("R is", "awesome", sep = "\n")
cat("R \t is \n awesome \\")

[1] 16

[1] 16

[1] "R is awesome"

R is awesomeR is
awesome
R 	 is 
 awesome \

In [113]:
log(100); log(exp(1)); log(100, 10)
round(exp(1), 2)
abs(-5); sqrt(25)

[1] 4.60517

[1] 1

[1] 2

[1] 2.72

[1] 5

[1] 5

In [139]:
x <- 1:5 * 10
x <- c(x, 30)
x
sum(x); min(x); max(x)
mean(x)
median(x)
sd(x)
var(x)
as.numeric(names(sort(-table(x))[1]))

[1] 10 20 30 40 50 30

[1] 180

[1] 10

[1] 50

[1] 30

[1] 30

[1] 14.14214

[1] 200

[1] 30

In [184]:
tolower("Yo")
substr("R is awesome", 1, 8)
nchar("123")
x <- c(FALSE, TRUE, FALSE)
any(x)
all(x) # everything true -> true
which(x)

[1] "yo"

[1] "R is awe"

[1] 3

[1] TRUE

[1] FALSE

[1] 2

In [183]:
x <- c(1, 3, 2)
length(x)
class(x)
typeof(x)
is.na(x); is.numeric(x)
unique(x)
sort(x); rev(x)

[1] 3

[1] "numeric"

[1] "double"

[1] FALSE FALSE FALSE

[1] TRUE

[1] 1 3 2

[1] 1 2 3

[1] 2 3 1

In [ ]:
fn <- function(x){
    x + 1
    # 1000
}
fn(5) * 5

[1] 30

In [250]:
fn <- function(x, b){
    (2 * x + b) ** 1/2
}
fn(1, 2)

[1] 2

In [257]:
tempInC <- function(F){
    5/9 * (F - 32)
}
tempInC(100)

[1] 37.77778

In [266]:
bmi <- function(w, h){
    w/(h/100)**2
}
bmi(70, 170)

[1] 24.22145

In [267]:
pi

[1] 3.141593

In [16]:
fn <- function(r) {
  p <- 2 * pi * r
  a <- pi * r ** 2
  return(c(p, a))
}
fn(5)

[1] 31.41593 78.53982